/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#3c475a",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#111c2d",
        "surface-variant": "#dfe3e7",
        "surface-container-lowest": "#ffffff",
        background: "#f6fafe",
        "primary-container": "#1e293b",
        "on-tertiary-fixed": "#001e2f",
        "on-background": "#171c1f",
        "surface-bright": "#f6fafe",
        "on-error-container": "#93000a",
        "on-secondary-container": "#fffbff",
        "primary-fixed-dim": "#bcc7de",
        tertiary: "#001624",
        "tertiary-fixed-dim": "#89ceff",
        "inverse-surface": "#2c3134",
        surface: "#f6fafe",
        "surface-container-high": "#e4e9ed",
        "surface-container": "#eaeef2",
        "outline-variant": "#c5c6cd",
        "tertiary-container": "#002c42",
        "on-tertiary-fixed-variant": "#004c6e",
        "inverse-on-surface": "#edf1f5",
        secondary: "#bc0007",
        "surface-container-low": "#f0f4f8",
        "on-surface": "#171c1f",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-primary": "#bcc7de",
        "on-surface-variant": "#45474c",
        "on-primary-container": "#8590a6",
        primary: "#091426",
        outline: "#75777d",
        "tertiary-fixed": "#c9e6ff",
        "surface-container-highest": "#dfe3e7",
        "primary-fixed": "#d8e3fb",
        "on-secondary-fixed": "#410001",
        "on-error": "#ffffff",
        "surface-dim": "#d6dade",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary-container": "#0099d9",
        "secondary-fixed": "#ffdad5",
        "on-secondary-fixed-variant": "#930004",
        "secondary-fixed-dim": "#ffb4a9",
        "secondary-container": "#ea000c",
        "surface-tint": "#545f73"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "stack-sm": "0.5rem",
        "stack-lg": "2rem",
        "margin-page": "2rem",
        "container-max": "1440px",
        gutter: "1.5rem",
        "stack-md": "1rem"
      },
      fontFamily: {
        "mono-data": ["Geist", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      fontSize: {
        "mono-data": ["13px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
